### ISSUE TITLE
VSK website should mention state name as 'Jharkhand' and not 'Andhra Pradesh'

### ISSUE THREAD

**Issue by sagarihanda** [Sunbird-cQube/dashboard-ms#128]
Change in login screen
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/73831409/235341516-aced0d3a-a55e-4622-8002-2978148253de.png">

Change in home screen (where role selection happens)
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/73831409/235341535-12e3f28f-9f9a-4d08-ac62-6da35f548e38.png">

**Comment by ananya-jain1** [comment]
This is resolved.
